image: python:latest

before_script:
  - python -V
  - pip install coverage

Test:
  script:
  - python unit_test_compiler.py

Coverage:
  script:
  - coverage run --omit=unit_test_compiler.py unit_test_compiler.py
  - coverage report -m
